### ISSUE TITLE
People can't logout

### ISSUE THREAD

**Issue by frederic2ec** [dularion/streama#158] opened 2016-03-22 22:08 UTC
Hi,
Here an error, if the people want to logout this error happened...
![Error](http://puu.sh/nQgVr/8360f4f8fd.png)

Thank.

**Comment by Flex101** [comment] 2016-03-30 19:01
I'm getting this message every time I view the dashboard with a non-admin account

**Comment by dularion** [comment] 2016-03-30 20:41
Oh really? Damn. Will look into that asap

**Comment by dularion** [comment] 2016-04-19 09:49
Partially fixed with latest commit

**Comment by dularion** [comment] 2016-04-19 09:53
Fixed the message in the bottom right. But I can't reproduce the logout issue. It works for me. Can you check to make sure your base path is correct?

**Comment by ManuGithubSteam** [comment] 2017-01-14 15:04
Can't reproduce on 1.07 for me :-)

**Comment by dularion** [comment] 2017-01-16 16:07
Pls reopen if problem persist in latest release

**Closed by dularion** 2017-01-16 16:07 UTC
Labels: can't reproduce
