### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#577] opened 2018-03-02 10:24 UTC
1- make the android app [Allow to reproduce videos without login in the application]
2- make the language default can change
3- the [search by name and filter by tag] in discoverd movies don't work
4- can make a convert [orginial to 1080p and 720p] like this
![desktop screenshot 2018 03 02 - 13 15 18 61](https://user-images.githubusercontent.com/31727156/36894323-003dd7f8-1e1c-11e8-9332-708fc8227eac.png)

**Comment by Jeronimo95** [comment] 2018-03-12 22:30
**Please stop making single issues for multiple problems. **

1. Duplicate of #516.
2. Make its own issue.
3. Make its own issue.
4. A transcoding feature will be implemented, this has been discussed many times. See #440.

**Please stop making single issues for multiple problems. And please give us as much detail as you can about issues.**

**Closed by Jeronimo95** 2018-03-12 22:30 UTC

**Comment by muhanadali100** [comment] 2018-03-13 00:04
ok
