### ISSUE TITLE
Visually bad selecting subs option in videoplayer + changing name

### ISSUE THREAD

**Issue by LittlePinkel** [dularion/streama#463] opened 2017-11-01 14:59 UTC
As the title suggest, when someone tries to select subs i get this unreadable option: http://prntscr.com/h4usl4. Also, it would be nice if it didn't said what the name of the subtitle is, but the language (like English/German/Dutch/etc, same as netflix).

**Comment by dularion** [comment] 2017-11-01 15:01
hi, 
1: it looks like your CSS didnt build correctly. did you use the release-version or a self-built version? 
2: it does display the language, you have to enter it tho in the manage-files dialog where u added the subs

**Comment by LittlePinkel** [comment] 2017-11-01 15:03
Hi, i used the release version 1.3.0 without any changes. Thanks, will look in the manage-files dialog.

**Comment by dularion** [comment] 2017-11-01 15:04
oh damn, just tested it, youre right!

**Comment by majorcyto** [comment] 2017-11-06 04:30
I can confirm this as well, looks like the box container is missing or something...

**Comment by dularion** [comment] 2018-04-05 21:13
This will be auto-fixed in the next release, was just a style-rebuild issue it seems

**Closed** 2018-04-05 21:13 UTC
Labels: Bug
