### ISSUE TITLE
Error when accessing movie page via manage content

### ISSUE THREAD

**Issue by eGolono** [dularion/streama#211] opened 2016-08-13 16:53 UTC
After either uploading a video file or adding an external URL, I am unable to check the movie's edit page. I can still view the film via the player but I can't delete it or make any changes via the manage content page.

 This error comes up in the browser console when accessing the page (NOTE: I modified the URL to localhost for privacy): 
```
GET http://localhost:8080/movie/show.json?id=2 500 (Internal Server Error)

(anonymous function)	@	vendor.unminified.js:23727
v	@	vendor.unminified.js:23520
m	@	vendor.unminified.js:23230
(anonymous function)	@	vendor.unminified.js:27796
$eval	@	vendor.unminified.js:29058
$digest	@	vendor.unminified.js:28874
$apply	@	vendor.unminified.js:29166
(anonymous function)	@	vendor.unminified.js:30951
f	@	vendor.unminified.js:18453
(anonymous function)	@	vendor.unminified.js:18730
```

On a possibly unrelated note, I also frequently encounter a problem with upload's failing once reaching 100% despite doing them on a stable internet connection.

**Comment by gkiko** [comment] 2016-08-28 20:11
I'll mark this issue as duplicate of #217

**Closed by gkiko** 2016-08-28 20:11 UTC
Labels: duplicate
