### ISSUE TITLE
Distribute as docker image

### ISSUE THREAD

**Issue by dularion** [dularion/streama#51] opened 2015-08-02 14:52 UTC

**Comment by thomasleveil** [comment] 2015-08-03 13:57
A prerequisite for this feature is to be able to externalise some essential parts of the streama configuration.

The Docker way of managing app settings is to use environment variables. The streama Grails application should somehow manage to read settings from the following environment variables:

- [ ] DataSource.groovy related:
  - MYSQL_HOST
  - MYSQL_PORT 
  - MYSQL_DB 
  - MYSQL_USER
  - MYSQL_PASSWORD
- [ ] BASE_URL (to come up with `http://www.some.domain.tdl/streama` which will be use for the links in email for instance)
- [ ] EMAIL_FROM
- [ ] SMTP_HOST and SMTP_PORT

I suppose there will be a need for other environment variables, but for now those are the one from the top of my head.

Once streama will be able to start from a war taking into account those environment variables, a Dockerfile will be easier to come up with.

**Comment by dularion** [comment] 2015-08-03 13:59
I agree with all of the above, except for base_url as this is already part of the settings-configuration (so it works via values in the database, not any config file).

**Comment by thomasleveil** [comment] 2015-08-03 14:03
> I agree with all of the above, except for base_url

list of variable updated

**Comment by dularion** [comment] 2015-08-03 14:04
And for email from, smtp host and smtp port we could also use the db. the only thing that cant be in the db is the db connection itself.

**Comment by thomasleveil** [comment] 2015-08-03 14:08
I do a bit of sysadmin as part of my job, and I find it more convenient to configure all _environment related_ settings with just an external config file or environment variables. As a sysadmin I don't want to have to know some of the application internals to be able to have it set up correctly ; In other words, it is not convenient to have to figure out where in the database should a setting be set.

**Comment by dularion** [comment] 2015-08-03 14:11
no, but what if it is done, like the base_url, in a settings page that is part of the GUI? The db-connection will likely never change on one and the same server, but the "from-email-address" may very well change often. shouldn't that then be more easily accessible, for instance via the GUI?

**Comment by thomasleveil** [comment] 2015-08-03 14:15
I agree drawing the line to tell apart settings which are _system related_ from those that are _application related_ can be tricky for some of those settings.

Anyway, other thing to consider is the ease of implementation for the docker image. It is straight forward to come up with a docker image that manages all settings as environment variable. However if the docker image would be to write some data in a mysql database on first boot, that would start to be a mess (init shell script, wait for db to be up before updating, etc)

**Comment by InfernoZeus** [comment] 2015-08-03 14:22
There are a couple of other alternatives: 
  * Mounting a config file via Docker volumes
  * Using an external key/value store, such as etcd

**Comment by dularion** [comment] 2015-08-03 14:24
Its grails that handles the writing of default-data, in a bootstrap.groovy. And for grails to run, the mysql has to be there anyway. So my suggestion would be to only put the most critical information in the external config which is required for grails to run. everything else can be handled by grails itself.

**Comment by thomasleveil** [comment] 2015-08-03 14:54
ok, todo list updated in [1st comment](https://github.com/dularion/streama/issues/51#issuecomment-127245083)

**Comment by dularion** [comment] 2015-08-03 14:55
But I don't want to overrule your judgement, I truly don't! I really like this dialogue, and am open to counter-arguments :)

**Comment by thomasleveil** [comment] 2015-08-03 14:56
Don't worry, we just have to agree on a starting point. We'll come up with a 1st docker image and once it starts to be used suggestions will pour ;)

**Comment by InfernoZeus** [comment] 2015-08-03 15:17
Something else to consider when dockerizing this is where will the actual video files be stored? Should they be contained in the Docker container itself, or just in a mounted volume?

**Comment by thomasleveil** [comment] 2015-08-03 16:04
Video files MUST be on a mounted volume as the docker container layered file system (copy-on-write) isn't providing good read/write performances in most cases.

Also, [best practices](https://docs.docker.com/articles/dockerfile_best-practices/#containers-should-be-ephemeral) encourage docker containers to be disposable. That implies docker containers must not persist data themselves, they are just holding the application code/binaries and running them along with conf (from environment or mounted conf file). This also complies with the [12 factor app](http://12factor.net/) manifesto.

**Comment by stramel** [comment] 2015-08-03 16:23
:+1: For docker image

I also agree with @thomasleveil. Mounted Volume and disposable containers running only the application code/binaries.

**Comment by dularion** [comment] 2015-08-03 16:29
agreed. Although, and now this is only my lack of docker experience, but doesnt the database reset every time you restart the docker image? That is, if the database only exists inside of docker. Or am I wrong?

**Comment by stramel** [comment] 2015-08-03 16:48
I'm not experienced with Docker either but its seems to me that it would store the database data outside the docker image? https://docs.docker.com/reference/builder/#volume

**Comment by dularion** [comment] 2015-08-03 16:51
Ah ok, yea.. that would be good. And necessary.

**Comment by InfernoZeus** [comment] 2015-08-03 16:59
Yep, using data volumes or data volume containers is [the official approach](https://docs.docker.com/userguide/dockervolumes/) to persisting data across multiple runs. 

> Video files MUST be on a mounted volume as the docker container layered file system (copy-on-write) isn't providing good read/write performances in most cases.

@thomasleveil It doesn't actually have to be a mounted volume from the host. A volume itself should avoid UFS. Good point about r/w performance, I hadn't considered that.

**Comment by thomasleveil** [comment] 2015-08-03 17:53
For the database, it would be another container dedicated to provide the mysql service. The official [mysql docker image](https://registry.hub.docker.com/_/mysql/) gives instructions on how to persist the mysql data.

**Comment by lhw** [comment] 2015-08-03 18:19
Heh. I thought the same. Here is a first version I created a few hours ago https://registry.hub.docker.com/u/r0lhw/docker-streama/

**Comment by whatevercode** [comment] 2015-08-03 19:24
oh.. we were working on the same. 
https://registry.hub.docker.com/u/whatever/streama/

```
docker run -d-p 8080:8080 -p 4000:4000 -v /data:/data -e “MYSQL_HOST=mysqlhost” -e “MYSQL_port=3306” -e “MYSQL_DB=streama” -e “MYSQL_USER=streama” -e “MYSQL_PASSWORD=streama” whatever/streama
```
happy to merge or use yours.

**Comment by lhw** [comment] 2015-08-03 22:15
The only thing I don't really like about my version is that due to the config being compiled into the code it needs to compile the config on each start as the host/ip etc might change between starts. And I currently don't see a way around it. Can't find anything about configs or envs in your setup.
Anyway, the rest is working pretty good right now.

As it stands I would prefer my setup as it can produce reproducible/automated builds and builds from source.

**Comment by thomasleveil** [comment] 2015-08-03 23:17
@lhw, maybehttp://johnrellis.blogspot.fr/2010/11/grails-quick-tip-external-configs.html?m=1 could change that

**Comment by lhw** [comment] 2015-08-04 09:35
@whatevercode already added an extra environment to the datasource which would allow for an ENV based config. I'll do a pull request later to change those names to the corresponding default ENVs and then the recompile wont be necessary anymore.

**Comment by thomasleveil** [comment] 2015-08-04 09:54
I like the way @whatevercode implemented this with the `docker` section in `DataSource.groovy`

**Comment by mikaelhg** [comment] 2015-08-07 16:17
Does the image from @whatevercode actually work for someone, with an empty database?

**Comment by dularion** [comment] 2015-08-14 14:25
He may not be very active at the moment (busy with his day-job). if you want to suggest an alternative approach, feel free :)

**Comment by baptistedonaux** [comment] 2015-09-17 13:27
@whatevercode I try to run your image (you have already build the image) but when I follow localhost:8080, I have an 404 status. You show the error ?

**Comment by lhw** [comment] 2015-09-29 07:54
Mhm I tried updating my docker image too the new environment in DataSource and I also fails to create the tables, same as the @whatevercode image. Anything I am missing here? Shouldn't these frameworks try an automatic migration/creation of the tables?

**Comment by HazWard** [comment] 2015-12-15 17:50
Do I have to create a MySQL database before using the Docker image or does the image takes care of that?

**Comment by gkiko** [comment] 2015-12-16 16:58
@HazWard current docker config uses Tomcat 8 as base image. So I don't think the image contains database.

**Comment by gkiko** [comment] 2016-09-01 20:52
closing in favor of #197

**Closed by gkiko** 2016-09-01 20:52 UTC
Labels: enhancement
