### ISSUE TITLE
Ability to add files that are already there?

### ISSUE THREAD

**Issue by jennygreene88** [dularion/streama#235] opened 2016-12-18 06:37 UTC
I'd like to add files to Streama that are *already on* the server.

I have ~300 GB of files sitting on my server happily ready to stream. Copying them into the Streama uploads folder has them show up in the file manager as 'Only existing on hard drive', but there's seemingly no way to add them to the library, to link them with any description, etc. It wants me to drag-and-drop upload my files. But that would take me around 3 months on my connection and cost about $170 in data fees. The files are already sitting right there in a format perfect for streaming, I would really love the ability to just tell Streama "check this folder."

**Comment by seffignoz** [comment] 2017-01-12 14:38
+1

**Comment by dexafree** [comment] 2017-01-12 21:59
Just came to say the same. Also, it would be great if it could traverse the subfolders.
I have it pointed to my transmission-daemon download folder, so the flow would be pretty simple:

1. Put something to download on transmission
2. Open streama
3. Select the file, link it to the show/movie
4. Personal Netflix!

**Comment by ManuGithubSteam** [comment] 2017-01-14 14:44
This is possible with the new 1.07 beta :-) 
I'm in the same boat as you two and it works very well.
However the folders for "local file add" are not ordered in any way so its hard to find a specific folder but it is a start :-)

**Comment by dularion** [comment] 2017-01-15 22:35
Is this a duplicate of https://github.com/dularion/streama/issues/66?

**Closed** 2017-01-17 21:10 UTC
Labels: duplicate
