### ISSUE TITLE
No trailers in 1.011

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#274] opened 2017-01-23 12:56 UTC
Hi

I noticed there are no trailer/preview windows anymore in the 11. version of streama.

Is it a setting to be turned on ?

Thanks

![screenshot_20170123_135619](https://cloud.githubusercontent.com/assets/3456994/22204727/c67e06ea-e173-11e6-82e1-a2d94c4e9ad8.png)

**Comment by dularion** [comment] 2017-01-23 13:43
Hm, it works for me. Can you check the network tab in the console and see if something gets suppressed that looks like youtube? also,  is it for all movies or only this particular one?

**Comment by ManuGithubSteam** [comment] 2017-01-23 17:06
It's on all videos also the ones i saw trailers before.

I don't block anything on my nas network wise. What network tab do you mean ?

**Comment by dularion** [comment] 2017-01-23 17:40
Chrome developer tools (f12) and then among other tabs there's one called network. Keep it open and reload the page and see if you can see anything relating to YouTube (you can also search through all the requests). Also check the console in general for Javascript errors

**Comment by ManuGithubSteam** [comment] 2017-01-24 13:41
Here is the info. I don't see any requests :-(

Any other info you need ?

![screenshot_20170124_130905](https://cloud.githubusercontent.com/assets/3456994/22249424/33cdea56-e243-11e6-9167-4cc4242eb73b.png)
![screenshot_20170124_131004](https://cloud.githubusercontent.com/assets/3456994/22249422/33cc92e6-e243-11e6-9829-c7021666506e.png)
![screenshot_20170124_131029](https://cloud.githubusercontent.com/assets/3456994/22249423/33cd18e2-e243-11e6-9da5-5c6ec851e600.png)

**Comment by dularion** [comment] 2017-01-29 22:00
Hm, I cannot reproduce this issue for the life of me :( any way you could give me temporary admin access to this?

**Comment by ManuGithubSteam** [comment] 2017-01-31 18:15
Hi dularion,
Unfortunately it runs only locally and at the moment i have no time to fiddle around to make it accessible from the net. Sorry.
I will come back to it, when i have more time. 

Can i help in any other way ?
Thanks for trying!

**Comment by dularion** [comment] 2017-03-26 20:17
Unfortunately I still cannot reproduce is. Is anyone else experiencing this? 
I will close this issue until either you or someone else can help me track down this behaviour

**Closed by dularion** 2017-03-26 20:17 UTC
Labels: Awaiting Feedback, bug, can't reproduce
