### ISSUE TITLE
Error 404 when run the application

### ISSUE THREAD

**Issue by andyalonzo** [dularion/streama#150] opened 2016-03-10 21:00 UTC
Hello, i'm under Archlinux, and i tried to install streama but it gives me an 404 error when try to acces to the web ui.
I have installed Oracle Java 7

This is my log
`cd streama
| Done creating WAR target/streama-0.1.war
| Running Grails application
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/home/aalonzo/.grails/wrapper/2.4.4/grails-2.4.4/dist/grails-plugin-log4j-2.4.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/home/aalonzo/Documents/Projects/streama/target/work/tomcat/webapps/ROOT/WEB-INF/lib/grails-plugin-log4j-2.4.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
| Error log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
| Error log4j:WARN Please initialize the log4j system properly.
| Error log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Configuring Spring Security Core ...
... finished configuring Spring Security Core
2016-03-10 14:52:40,362 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Server returned HTTP response code: 401 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key=null
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key=null
	at streama.TheMovieDbService.getMovieGenres(TheMovieDbService.groovy:34)
	at streama.MigrationService.$tt__importMovieDbGenres(MigrationService.groovy:34)
	at BootStrap$_closure1.doCall(BootStrap.groovy:14)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2016-03-10 14:52:40,363 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing Grails: Server returned HTTP response code: 401 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key=null
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key=null
	at streama.TheMovieDbService.getMovieGenres(TheMovieDbService.groovy:34)
	at streama.MigrationService.$tt__importMovieDbGenres(MigrationService.groovy:34)
	at BootStrap$_closure1.doCall(BootStrap.groovy:14)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key=null
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:126)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.themoviedb.org/3/genre/movie/list?api_key=null
	at streama.TheMovieDbService.getMovieGenres(TheMovieDbService.groovy:34)
	at streama.MigrationService.$tt__importMovieDbGenres(MigrationService.groovy:34)
	at BootStrap$_closure1.doCall(BootStrap.groovy:14)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	... 4 more
Error listenerStart
Context [] startup failed due to previous errors
The web application [] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
The web application [] appears to have started a thread named [PoolCleaner[744613686:1457643139414]] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [net.sf.ehcache.CacheManager@29fcf463] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.Video.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.ViewingStatus.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.User.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.Role.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.TvShow.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.TvShow.episodes.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] appears to have started a thread named [streama.Video.files.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [] created a ThreadLocal with key of type [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2] (value [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2@27f90229]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
| Server running. Browse to http://localhost:8080/
| Server running. Browse to http://localhost:8080/
`

**Comment by dularion** [comment] 2016-03-10 22:58
Hi!
I know what the issue is and I will fix it asap tomorrow morning CET. Sorry for the inconvenience!

**Comment by jaruba** [comment] 2016-03-11 05:35
Interested in this too :)

**Comment by dularion** [comment] 2016-03-11 07:04
Ok it should be fixed now! Again, sorry for the inconvenience

**Closed** 2016-03-11 07:04 UTC

**Comment by jaruba** [comment] 2016-03-11 07:18
Awesome, thanks!

**Comment by shraderdm** [comment] 2016-05-21 02:48
I am currently having this issue. In chrome I get a blank screen, and in IE I get a 404. If I inspect the page it is also getting the 404 in chrome.

Any advice to fix this?
