### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

### ISSUE THREAD

**Issue by imkimchi** [dularion/streama#279] opened 2017-01-26 22:58 UTC

**Comment by dularion** [comment] 2017-01-29 22:13
I cannot reproduce this issue, can you tell me a bit more about it? How did you get it? what were you doing? which version did you use? which browser?

**Comment by gaiserik** [comment] 2017-02-09 02:02
Same issue both on streama build form master and 1.0.11 source code.

Tried on a debian docker container with openjdk7 and grails 3.1.14 with ./gradlew
Tried on windows  build with jdk8 (1.8) grails 3.1.14, gradle 2.9 with IntelliJ.

After admin logon, blank page on Chrome and Firefox :

```
Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3  vendor-9de9f4da324cfc0ed0992d04f0333e25.js:716:111
ReferenceError: _ is not defined[En savoir plus]  streama-2e069405fd8ee15e18911d6a628f4cb5.js:2:47
Error: [$injector:modulerr] Failed to instantiate module streama due to:
[$injector:nomod] Module 'streama' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.10/$injector/nomod?p0=streama
h/<@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:285:359
Sc/</</<@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:304:79
b@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:303:96
Sc/</<@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:303:380
m/<@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:319:202
b@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:286:303
m@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:319:50
Bb@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:322:437
M/g@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:299:185
M@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:299:498
Vb@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:298:265
@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:591:459
g/</n@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:190:378
g/</q<@http://localhost:8080/assets/vendor-9de9f4da324cfc0ed0992d04f0333e25.js:191:191

http://errors.angularjs.org/1.4.10/$injector/modulerr?p0=streama&p1=%5B%24injector%3Anomod%5D%20Module%20'streama'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.10%2F%24injector%2Fnomod%3Fp0%3Dstreama%0Ah%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A285%3A359%0ASc%2F%3C%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A304%3A79%0Ab%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A303%3A96%0ASc%2F%3C%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A303%3A380%0Am%2F%3C%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A319%3A202%0Ab%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A286%3A303%0Am%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A319%3A50%0ABb%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A322%3A437%0AM%2Fg%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A299%3A185%0AM%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A299%3A498%0AVb%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A298%3A265%0A%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A591%3A459%0Ag%2F%3C%2Fn%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A190%3A378%0Ag%2F%3C%2Fq%3C%40http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fvendor-9de9f4da324cfc0ed0992d04f0333e25.js%3A191%3A191%0A  vendor-9de9f4da324cfc0ed0992d04f0333e25.js:285:359
```
Works fine with the published *.war.

Usually I use streama without database with :
`java -jar -Dgrails.env=production-no-mysql streama-1.0.11-0.1.war`

**Comment by gaiserik** [comment] 2017-02-15 13:08
In my case jQuery was updated to 3.x, solved by adding jquery dependency version on the build.gradle file.

**Comment by dularion** [comment] 2017-03-06 22:20
Closing for now, I think it might be resolved in one of the newer builds. please reopen if problem persists

**Closed by dularion** 2017-03-06 22:20 UTC
Labels: Awaiting Feedback, bug, can't reproduce, More Info required
