### ISSUE TITLE
Auto thumbnail in generic videos

### ISSUE THREAD

**Issue by robsonolivesa** [dularion/streama#381] opened 2017-05-26 02:39 UTC
Is it possible to capture the video image to use in thumbnail? Only in generic videos.

**Comment by dularion** [comment] 2017-06-27 20:10
Good idea! might not be so easy but I like the idea :)

**Comment by Jeronimo95** [comment] 2017-08-25 13:08
Duplicate of #194

**Closed by Jeronimo95** 2017-08-25 13:08 UTC
Labels: enhancement
