### ISSUE TITLE
Add an image preview to manually-added videos

### ISSUE THREAD

**Issue by asmartin** [dularion/streama#170] opened 2016-05-01 00:29 UTC
I have successfully uploaded a manually-added video (not in The Movie DB), however when I try and drag and drop an image file onto the video to use as the preview, nothing seems to happen (tested in both Chrome and Firefox). Is there another way to add an image preview, or would it be possible to add an upload button to the `Edit` screen for the video? Thanks!

**Comment by robsonolivesa** [comment] 2016-07-01 03:01
Any news about this issue?

**Comment by dularion** [comment] 2016-07-01 06:05
Oh, the file manager is only meant for subtitles and video files. For a poster image there is a different functionality that is not yet implemented for regular videos. By adding generic videos you can see how this feature works. I could implement that for shows and movies too, if there is no poster image. Just let me know if that is what you're looking for.

**Comment by asmartin** [comment] 2016-07-01 11:55
Yes I think that's what I'm looking for - so when I upload each episode, I
can select an image to associate with each

**Comment by dularion** [comment] 2016-07-01 12:21
Okay! I'll get on that then :)

**Comment by dularion** [comment] 2016-07-01 12:22
Btw, do I understand correctly, you want this for each individual episode?

**Comment by robsonolivesa** [comment] 2016-07-01 13:04
This functionality exists. I found. Tks

**Comment by asmartin** [comment] 2016-07-03 02:23
> Btw, do I understand correctly, you want this for each individual episode?

Yes, an image preview for each episode

**Comment by Jeronimo95** [comment] 2017-08-25 13:18
Duplicate of #194

**Closed by Jeronimo95** 2017-08-25 13:18 UTC
Labels: enhancement
