### ISSUE TITLE
Rate limit for TMDB API

### ISSUE THREAD

**Issue by siteripper** [dularion/streama#480] opened 2017-11-28 13:15 UTC
When I try to use the Matcher on more than a few files I get this error:

ERROR grails.app.services.streama.BulkCreateService - Error occured while trying to retrieve data from TheMovieDB. Please check your API-Key.

Then when doing "Add all found matches" he says "Internal Error" and wont add anything (not evben the ones he was able to match without the error above).
Console says:

ERROR org.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [POST] /file/bulkAddMediaFromFile.json
Cannot get property 'id' on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'id' on null object

**Comment by siteripper** [comment] 2017-11-28 13:32
TMDB has a limit fpr API-Requests:
"Our current limits are 40 requests every 10 seconds" (per IP)

This is probably causing the first error.

**Comment by Jeronimo95** [comment] 2017-11-29 23:49
We may have to implement some form of rate limiting for the API to keep it under 40req/10sec - especially when doing large operations.

Looking at the code the second error is caused by the first error. Since TheMovieDB API call fails, its variable is null and then we try and get the ID from the null object.
https://github.com/dularion/streama/blob/35e542ff32be38669d652947032479b96d579b34/grails-app/services/streama/BulkCreateService.groovy#L175

**Comment by dularion** [comment] 2017-12-08 20:06
Oh dang... Ok that makes sense. Wont be super easy tho

**Comment by Jeronimo95** [comment] 2018-03-25 01:51
Closing this in favor of #597

**Closed by Jeronimo95** 2018-03-25 01:51 UTC
Labels: Bug
