### ISSUE TITLE
Request - Image in TV Series Episode 

### ISSUE THREAD

**Issue by videojock** [dularion/streama#489] opened 2017-12-11 11:01 UTC
It would be great if there was an option to insert another image in the series episode as sometimes the Movie  Database are late updating or not at all.

Maybe in the latest final release?

**Comment by dularion** [comment] 2017-12-11 11:02
Duplicate of this: https://github.com/dularion/streama/issues/488

**Closed by dularion** 2017-12-11 11:02 UTC
