### ISSUE TITLE
Subscription Center - Like netflix allow people to purchase access

### ISSUE THREAD

**Issue by mosquedaoscar** [dularion/streama#231] opened 2016-12-04 13:46 UTC
It would be interesting to give the opportunity to people who want to sell their own videos, create a paid access system, with paypal

**Comment by z3ntu** [comment] 2016-12-04 14:27
Duplicate of #221

**Comment by mosquedaoscar** [comment] 2016-12-04 15:31
It is not duplicated because it does not support downloads or file sharing, only paid access!

**Comment by z3ntu** [comment] 2016-12-04 17:37
> Subscription Center - Like netflix allow people to purchase access

#221 is a list of features the person wants to see implemented.

**Comment by mosquedaoscar** [comment] 2016-12-04 21:43
I would particularly like to see this modification implemented

**Comment by chopraaa** [comment] 2016-12-25 04:09
Pointless modification that will only be used for personal benefit.

Move on. Much more important things to work on.

**Comment by Jeronimo95** [comment] 2017-08-25 13:32
I agree with @chopraaa. I'm going to close this for the same reason I closed #159. I don't think streama should be the one adding the Subscription system. If people want to use streama as a base for something like that they can integrate it themselves.

**Closed by Jeronimo95** 2017-08-25 13:32 UTC
Labels: question
