### ISSUE TITLE
Cannot install without a moviedb account

### ISSUE THREAD

**Issue by ericalbers** [dularion/streama#189] opened 2016-06-15 00:03 UTC
You must register for a moviedb account in order to use the program it will NOT work without an API key.
So the NSA/everyone can see what your watching.
I modded mine to fix this, will fork.

**Comment by z3ntu** [comment] 2016-06-15 05:54
You know, the the API key is only used for information about new shows you add...?

**Comment by dularion** [comment] 2016-06-29 20:36
I'd appreciate a PR for this :)

**Comment by SajeOne** [comment] 2016-07-06 22:58
duplicate of #125 as well. If you could submit a pull request with your custom version I would greatly appreciate it. :)

**Comment by moeinrahimi** [comment] 2017-01-25 17:52
it would be awesome if moviedb was optional and there was alternative services

**Comment by dularion** [comment] 2017-01-25 19:49
It would be optional with 1.0.11

**Comment by Jeronimo95** [comment] 2017-08-25 13:05
Duplicate of #125

**Closed by Jeronimo95** 2017-08-25 13:05 UTC
Labels: enhancement
