### ISSUE TITLE
Error SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by PhilW86** [dularion/streama#102] opened 2015-11-26 14:52 UTC
I always get the following error message while trying to start streama:

```
| Done creating WAR target/streama-0.1.war
| Running Grails application
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/root/.grails/wrapper/2.4.4/grails-2.4.4/dist/grails-plugin-log4j-2.4.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/home/me/streama/target/work/tomcat/webapps/streama/WEB-INF/lib/grails-plugin-log4j-2.4.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
| Error log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
| Error log4j:WARN Please initialize the log4j system properly.
| Error log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Configuring Spring Security Core ...
... finished configuring Spring Security Core
| Server running. Browse to http://localhost:8080/streama
| Server running. Browse to http://localhost:8080/streama
```

Trying to open the URL just brings up a blank page. I tried to solve this problem by myself and found some hints, e.g. to set an exclusion like:
```<exclusions>
    <exclusion>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-log4j12</artifactId>
    </exclusion>
</exclusions> 
```
However, I didn't find a file called "pom.xml". Adding these lines to familiar looking files (I tried a lot!) didn't help either.

Do you have any suggestion on how to solve this issue?
Thank you in advance!

P.S.: Do you already have a rough estimation when features like file crawler and media conversion will be added?

**Comment by dularion** [comment] 2015-11-28 09:14
Hm... I have never seen an error like this before. 
How did you install grails? How are you running streama? with run-app or through tomcat? What version ubuntu are you running? or is a local machine? What version of java are you using? Try to give me as much information like that as possible, that way we can narrow it down (maybe).

Regarding your question: I have no estimate currently... I've looked into both, and the file crawler is higher on my list than media conversion. The problem with media conversion is the fact that it has to happen async, and that I have to queue the files, otherwise it is too much load on any server.. Video conversion is quite heavy for any server, really. So I am still working on a plan for that. But of course I hope that I will get all of this into streama soon-ish! but it is very unlikely that that will happen before xmas this year.

**Comment by gkiko** [comment] 2015-11-29 15:37
This issue is duplicate of #40 

I fixed the issue by restarting the server

**Comment by dularion** [comment] 2015-12-05 17:25
@PhilW86, does the suggestion by @gkiko help?

**Comment by dularion** [comment] 2016-03-12 14:02
Reopen if the problem persists.

**Closed by dularion** 2016-03-12 14:02 UTC
Labels: bug
