### ISSUE TITLE
Question: Why Require a Base Path Instead of Just Binding to The Port on All Interfaces?

### ISSUE THREAD

**Issue by mongomay69** [dularion/streama#334] opened 2017-03-06 21:34 UTC
i may not know what i'm talking about and if i don't feel free to tell me.

**Comment by dularion** [comment] 2017-03-24 22:50
Yes you are completely right in this. This is definitely one for the roadmap

**Comment by Shrinks99** [comment] 2017-05-12 16:36
Was this included in V1.1?

**Comment by Jeronimo95** [comment] 2017-08-25 13:42
Duplicate of #282

**Comment by mongomay69** [comment] 2017-08-25 17:58
not quite but similar

**Comment by Jeronimo95** [comment] 2017-08-25 23:04
Sorry, you are quite right. I should have closed the other issue. I think the way to go is to remove the need to enter a base URL.

**Comment by Jeronimo95** [comment] 2018-01-03 06:47
This should be ready for the next release. If anyone wants to test the changes you can use the branch [JR/feature/BasePathRemoval](https://github.com/dularion/streama/tree/JR/feature/BasePathRemoval).

If you don't want to compile it yourself you can download a WAR here:  
http://streamabuilds.s3-website-us-east-1.amazonaws.com/?prefix=origin/JR/feature/BasePathRemoval/

I don't think the base path is used anywhere other than the video player and the invite links. It will still be used for the invite links, but for the video player it should just work with the relative URL.

**Closed** 2018-01-04 14:23 UTC
Labels: Enhancement

**Comment by Jeronimo95** [comment] 2018-01-04 14:28
This change is now merged with master and will be in the v1.5.0 release.

**Comment by jguerinet** [comment] 2018-01-04 14:30
Fantastic! This was something I had brought up back in January last year and I tried to solve by myself but did not have the necessary knowledge to understand what was going on. I checked your PR though, it seems so simple I can't believe I couldn't do figure it out... In any case, thank you!
