### ISSUE TITLE
smart TV and IOS

### ISSUE THREAD

**Issue by guruiteu** [dularion/streama#531] opened 2018-01-09 17:12 UTC
Hey, i have a Philips smart tv (not a android TV) it has limited aplications in the shop. Only one streaming application is Netflix and Deezer.  I traid to open a streama hosted movie on i't using browser, but it dosn't play the movie loanding all the time then it show a error about HTML 5 the same problem i have on ipad and on iphone.

Will there be a IOS aplication or solution for the HTML 5 so that on Smart TV and IOS can watch movies?

Thank you

**Comment by Jeronimo95** [comment] 2018-01-09 21:26
iOS duplicate of #70. Smart TV duplicate of #75.

**Closed** 2018-01-09 21:26 UTC
